#!/usr/bin/env python3

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
import os

def setup_chrome_options():
    chrome_options = Options()
    chrome_options.add_argument("--headless") # Ensure GUI is off
    chrome_options.add_argument("--no-sandbox")

    return chrome_options


def get_chromedriver_service():
    # Set path to chromedriver as per your configuration
    
    webdriver_service = Service(os.getcwd()+"/chromedriver")
    return webdriver.Chrome(service=webdriver_service, options=setup_chrome_options())


def exec_login(username, password):
    """ """
    
    username_field = driver.find_element(By.NAME, "username")
    password_field = driver.find_element(By.NAME, "password")
    continue_button = driver.find_element(By.XPATH, "//input[@type='submit']")
    
    username_field.send_keys(username)
    password_field.send_keys(password)
    continue_button.click()


def login_to_wifi():
    """ """
    
    webpage_html = driver.find_element(By.TAG_NAME, "html").get_attribute("innerHTML")
    
    if ("Welcome to the AFCHO FREE WIFI!" in webpage_html):
        
        username = "stut609"
        password = "bjnfok"
        
        exec_login(username, password)
        print("[-] CONNECTED")
        
    elif ("<td>Connected</td>" in webpage_html):
        print("[x] Already connected")
    else:
        print("[xx]There was an error")
    

    driver.quit()
    
    

driver = get_chromedriver_service()
driver.get("http://172.16.0.1/login")
login_to_wifi()
